version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13.2
    container_name: bewise
    restart: always
    command: -p 4500
    expose:
      - 4500
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: