version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/core
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13.2
    container_name: bewise
    restart: always
    command: -p 4500
    ports:
      - 4500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: