"""create

Revision ID: 3d92e0d832ef
Revises: 
Create Date: 2023-05-25 13:48:43.574693

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3d92e0d832ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_question',
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('airdate', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('random_question')
    # ### end Alembic commands ###
